version: 2
jobs:
  build:
    working_directory: ~/mediatidy
    # The primary container is an instance of the first list image listed. Your build commands run in this container.
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: install packages
          command: npm install
